import type { StatePreset } from '../types';

export const STATE_CATEGORIES = [
  'Reacciones',
  'Ciclo de vida',
  'Ciclo de producto',
  'Morfos de agente',
  'Interacción',
];

export const STATE_PRESETS: StatePreset[] = [
  // --- REACCIONES (16) ---
  {
    id: 'happy',
    name: 'Feliz',
    category: 'Reacciones',
    description: 'Corazón rosa con ojos kawaii y sonrisa amplia',
    data: {
      silhouette: 'heart',
      color: '#F2A9B8',
      eyeType: 2,
      eyeOpen: 1.0,
      eyeScale: 1.05,
      mouthType: 0,
      mouthCurve: 0.8,
      mouthOpen: 0.25,
      cheek: 0.6,
      hasBrows: false,
      transitionType: 'smooth',
    },
  },
  {
    id: 'excited',
    name: 'Emocionado',
    category: 'Reacciones',
    description: 'Estrella dorada con ojos brillantes, sonrisa y entusiasmo',
    data: {
      silhouette: 'starburst-puff',
      color: '#F2CB4E',
      eyeType: 21,
      eyeOpen: 1.0,
      eyeScale: 1.2,
      mouthType: 6,
      mouthCurve: 0.9,
      mouthOpen: 0.8,
      cheek: 0.8,
      hasBrows: false,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'surprised',
    name: 'Sorpresa',
    category: 'Reacciones',
    description: 'Fantasma naranja con ojos abiertos de par en par y boca "O"',
    data: {
      silhouette: 'ghost-blob',
      color: '#FFAA64',
      eyeType: 13,
      eyeOpen: 1.0,
      eyeScale: 1.25,
      mouthType: 1,
      mouthOpen: 0.9,
      hasBrows: true,
      browY: -4,
      browTilt: -6,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'angry',
    name: 'Furia / Enojo',
    category: 'Reacciones',
    description: 'Llama roja con cejas inclinadas y boca apretada',
    data: {
      silhouette: 'flame-blob',
      color: '#E85B64',
      eyeType: 3,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 20,
      mouthCurve: -0.6,
      hasBrows: true,
      browTilt: -18,
      browY: -2,
      transitionType: 'snappy',
    },
  },
  {
    id: 'sad',
    name: 'Tristeza',
    category: 'Reacciones',
    description: 'Gota azul con lágrimas cayendo y comisuras hacia abajo',
    data: {
      silhouette: 'teardrop-blob',
      color: '#5B8FD4',
      eyeType: 16,
      eyeOpen: 0.9,
      eyeScale: 1.0,
      mouthType: 12,
      mouthCurve: -0.8,
      tears: 1,
      hasBrows: true,
      browTilt: 12,
      browY: -1,
      transitionType: 'smooth',
    },
  },
  {
    id: 'confused',
    name: 'Confuso',
    category: 'Reacciones',
    description: 'Blob con garabato animado en la cabeza y boca zigzag',
    data: {
      silhouette: 'droopy-blob',
      color: '#F2DF80',
      eyeType: 11,
      eyeOpen: 0.9,
      eyeScale: 1.0,
      mouthType: 2,
      mouthCurve: 0.2,
      scribble: 1,
      gazeX: 6,
      gazeY: -2,
      hasBrows: true,
      browTilt: 10,
      browY: 0,
      transitionType: 'smooth',
    },
  },
  {
    id: 'suspicious',
    name: 'Desconfiado',
    category: 'Reacciones',
    description: 'Cápsula verde con mirada de reojo y ceja inclinada',
    data: {
      silhouette: 'capsule',
      color: '#7ED321',
      eyeType: 22,
      eyeOpen: 0.75,
      eyeScale: 1.05,
      mouthType: 11,
      mouthCurve: -0.3,
      gazeX: 10,
      gazeY: 0,
      hasBrows: true,
      browTilt: -12,
      browY: 0,
      transitionType: 'smooth',
    },
  },
  {
    id: 'laughing',
    name: 'Risas',
    category: 'Reacciones',
    description: 'Blob redondo amarillo con ojos de arco risueño y gran lengua',
    data: {
      silhouette: 'round-blob',
      color: '#F2CB4E',
      eyeType: 1,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 23,
      mouthCurve: 0.9,
      mouthOpen: 0.9,
      cheek: 0.7,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'scared',
    name: 'Asustado',
    category: 'Reacciones',
    description: 'Gota violeta con ojos saltones y gotas de sudor frío',
    data: {
      silhouette: 'teardrop-blob',
      color: '#7C4DFF',
      eyeType: 26,
      eyeOpen: 1.0,
      eyeScale: 1.25,
      mouthType: 19,
      mouthCurve: -0.5,
      mouthOpen: 0.7,
      sweat: 1,
      transitionType: 'snappy',
    },
  },
  {
    id: 'celebrate',
    name: 'Celebración',
    category: 'Reacciones',
    description: 'Estrella brillante dorada con giro y salto',
    data: {
      silhouette: 'starburst-puff',
      color: '#FFD600',
      eyeType: 24,
      eyeOpen: 1.0,
      eyeScale: 1.2,
      mouthType: 6,
      mouthCurve: 0.9,
      mouthOpen: 0.8,
      cheek: 0.9,
      bounce: true,
      spin: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'proud',
    name: 'Orgulloso',
    category: 'Reacciones',
    description: 'Cápsula menta con media sonrisa de autosuficiencia',
    data: {
      silhouette: 'capsule',
      color: '#50E3C2',
      eyeType: 0,
      eyeOpen: 0.85,
      eyeScale: 1.05,
      mouthType: 24,
      mouthCurve: 0.6,
      cheek: 0.4,
      hasBrows: true,
      browTilt: -6,
      browY: -2,
      transitionType: 'smooth',
    },
  },
  {
    id: 'shy',
    name: 'Tímido',
    category: 'Reacciones',
    description: 'Corazón rojo con sonrojo intenso y mirada esquiva',
    data: {
      silhouette: 'heart',
      color: '#FF5252',
      eyeType: 14,
      eyeOpen: 0.7,
      eyeScale: 0.9,
      mouthType: 20,
      mouthCurve: 0.2,
      cheek: 1.0,
      gazeX: -6,
      gazeY: 4,
      transitionType: 'gentle',
    },
  },
  {
    id: 'playful',
    name: 'Pícaro',
    category: 'Reacciones',
    description: 'Squircle fucsia con guiño, lengua afuera y rebote',
    data: {
      silhouette: 'rounded-squircle',
      color: '#FF4081',
      eyeType: 10,
      eyeOpen: 1.0,
      eyeScale: 1.05,
      mouthType: 15,
      mouthCurve: 0.5,
      cheek: 0.6,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'bored',
    name: 'Aburrido',
    category: 'Reacciones',
    description: 'Óvalo gris con mirada inexpresiva fija y bocanada de aire',
    data: {
      silhouette: 'wide-oval',
      color: '#B9BDB6',
      eyeType: 28,
      eyeOpen: 0.6,
      eyeScale: 1.0,
      mouthType: 3,
      mouthCurve: 0,
      gazeX: 6,
      gazeY: 3,
      puff: 1,
      transitionType: 'gentle',
    },
  },
  {
    id: 'curious',
    name: 'Curioso',
    category: 'Reacciones',
    description: 'Huevo azul con ojos brillantes mirando arriba a la derecha',
    data: {
      silhouette: 'egg-oval',
      color: '#00B0FF',
      eyeType: 5,
      eyeOpen: 1.0,
      eyeScale: 1.15,
      mouthType: 1,
      mouthOpen: 0.4,
      gazeX: 7,
      gazeY: -3,
      hasBrows: true,
      browTilt: 8,
      browY: -2,
      transitionType: 'smooth',
    },
  },
  {
    id: 'drowsy',
    name: 'Somnoliento',
    category: 'Reacciones',
    description: 'Óvalo beige con párpados caídos y gota de cansancio',
    data: {
      silhouette: 'wide-oval',
      color: '#E2E8D8',
      eyeType: 15,
      eyeOpen: 0.4,
      eyeScale: 1.0,
      mouthType: 3,
      mouthCurve: -0.2,
      sweat: 0.6,
      puff: 1,
      hasBrows: false,
      transitionType: 'gentle',
    },
  },

  // --- CICLO DE VIDA (6) ---
  {
    id: 'sleeping',
    name: 'Durmiendo',
    category: 'Ciclo de vida',
    description: 'Figura celeste relajada con Zzz flotando',
    data: {
      silhouette: 'soft-round',
      color: '#98C5E8',
      eyeType: 14,
      eyeOpen: 0.2,
      eyeScale: 0.95,
      mouthType: 3,
      mouthCurve: 0,
      zzz: 1,
      hasBrows: false,
      transitionType: 'gentle',
    },
  },
  {
    id: 'waking',
    name: 'Despertando',
    category: 'Ciclo de vida',
    description: 'Figura carmesí bostezando con ojos entreabiertos',
    data: {
      silhouette: 'soft-round',
      color: '#E3536C',
      eyeType: 14,
      eyeOpen: 0.5,
      eyeScale: 0.95,
      mouthType: 1,
      mouthOpen: 0.7,
      puff: 1,
      cheek: 0.3,
      transitionType: 'smooth',
    },
  },
  {
    id: 'listening',
    name: 'Escuchando',
    category: 'Ciclo de vida',
    description: 'Pera menta con atención receptiva y mirada atenta',
    data: {
      silhouette: 'pear-blob',
      color: '#A8D5BA',
      eyeType: 31,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 0,
      mouthCurve: 0.3,
      gazeX: -4,
      gazeY: 0,
      transitionType: 'smooth',
    },
  },
  {
    id: 'thinking',
    name: 'Pensando',
    category: 'Ciclo de vida',
    description: 'Squircle púrpura con mirada arriba y ceja levantada',
    data: {
      silhouette: 'rounded-squircle',
      color: '#BD10E0',
      eyeType: 0,
      eyeOpen: 0.9,
      eyeScale: 1.0,
      mouthType: 16,
      mouthCurve: 0.3,
      gazeX: 8,
      gazeY: -5,
      hasBrows: true,
      browTilt: 8,
      browY: -1,
      transitionType: 'smooth',
    },
  },
  {
    id: 'searching',
    name: 'Buscando',
    category: 'Ciclo de vida',
    description: 'Óvalo azul explorando con mirada diagonal rápida',
    data: {
      silhouette: 'oval',
      color: '#4A90E2',
      eyeType: 5,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 0,
      mouthCurve: 0.1,
      gazeX: -10,
      gazeY: -4,
      transitionType: 'snappy',
    },
  },
  {
    id: 'working',
    name: 'Trabajando',
    category: 'Ciclo de vida',
    description: 'Píldora negra con gafas de enfoque mirando abajo',
    data: {
      silhouette: 'pill-vertical',
      color: '#18181B',
      eyeType: 9,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 3,
      mouthCurve: 0,
      gazeX: 0,
      gazeY: 4,
      transitionType: 'smooth',
    },
  },

  // --- CICLO DE PRODUCTO (13) ---
  {
    id: 'loading',
    name: 'Cargando',
    category: 'Ciclo de producto',
    description: 'Round blob morado con ojos en espiral de procesamiento',
    data: {
      silhouette: 'round-blob',
      color: '#BD10E0',
      eyeType: 18,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 13,
      mouthCurve: 0,
      spin: true,
      transitionType: 'smooth',
    },
  },
  {
    id: 'uploading',
    name: 'Subiendo',
    category: 'Ciclo de producto',
    description: 'Estrella verde brillante transmitiendo datos',
    data: {
      silhouette: 'starburst-puff',
      color: '#00E676',
      eyeType: 24,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 6,
      mouthCurve: 0.8,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'notifying',
    name: 'Notificando',
    category: 'Ciclo de producto',
    description: 'Corazón coral con ojos de corazón y rebote de llamada',
    data: {
      silhouette: 'heart',
      color: '#FF6F61',
      eyeType: 6,
      eyeOpen: 1.0,
      eyeScale: 1.15,
      mouthType: 5,
      mouthCurve: 0.9,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'alerting',
    name: 'Alerta / Peligro',
    category: 'Ciclo de producto',
    description: 'Llama carmesí con ojos en cruz y nubes de tormenta',
    data: {
      silhouette: 'flame-blob',
      color: '#E85B64',
      eyeType: 7,
      eyeOpen: 1.0,
      eyeScale: 1.15,
      mouthType: 4,
      mouthCurve: -0.5,
      storm: 1,
      transitionType: 'snappy',
    },
  },
  {
    id: 'dictating',
    name: 'Dictando',
    category: 'Ciclo de producto',
    description: 'Pera rosa con boca abierta hablando',
    data: {
      silhouette: 'pear-blob',
      color: '#F2A9B8',
      eyeType: 0,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 6,
      mouthCurve: 0.6,
      mouthOpen: 0.8,
      transitionType: 'smooth',
    },
  },
  {
    id: 'writing',
    name: 'Escribiendo',
    category: 'Ciclo de producto',
    description: 'Huevo verde con mirada hacia abajo redactando',
    data: {
      silhouette: 'egg-oval',
      color: '#7ED321',
      eyeType: 0,
      eyeOpen: 0.9,
      eyeScale: 0.95,
      mouthType: 3,
      mouthCurve: 0.1,
      gazeX: 0,
      gazeY: 6,
      transitionType: 'smooth',
    },
  },
  {
    id: 'sending',
    name: 'Enviando',
    category: 'Ciclo de producto',
    description: 'Cápsula celeste kawaii despachando mensaje',
    data: {
      silhouette: 'capsule',
      color: '#00B0FF',
      eyeType: 2,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 9,
      mouthCurve: 0.7,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'receiving',
    name: 'Recibiendo',
    category: 'Ciclo de producto',
    description: 'Squircle lila recibiendo con rebote de llegada',
    data: {
      silhouette: 'rounded-squircle',
      color: '#7C4DFF',
      eyeType: 5,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 1,
      mouthOpen: 0.5,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'spawning',
    name: 'Nacimiento',
    category: 'Ciclo de producto',
    description: 'Estrella rosa surgiendo con gran sorpresa',
    data: {
      silhouette: 'starburst-puff',
      color: '#FF4081',
      eyeType: 13,
      eyeOpen: 1.0,
      eyeScale: 1.3,
      mouthType: 1,
      mouthOpen: 0.9,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'humming',
    name: 'Tarareando',
    category: 'Ciclo de producto',
    description: 'Round blob fucsia cantando con notas alegres',
    data: {
      silhouette: 'round-blob',
      color: '#F28FC2',
      eyeType: 1,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 18,
      mouthCurve: 0.6,
      cheek: 0.7,
      transitionType: 'smooth',
    },
  },
  {
    id: 'dragging',
    name: 'Arrastre',
    category: 'Ciclo de producto',
    description: 'Blob terracota con gotas de tensión elástica',
    data: {
      silhouette: 'droopy-blob',
      color: '#C47D68',
      eyeType: 29,
      eyeOpen: 0.85,
      eyeScale: 1.05,
      mouthType: 2,
      mouthCurve: -0.2,
      sweat: 0.5,
      transitionType: 'snappy',
    },
  },
  {
    id: 'bouncing',
    name: 'Rebotando',
    category: 'Ciclo de producto',
    description: 'Round blob verde con rebote alegre continuo',
    data: {
      silhouette: 'round-blob',
      color: '#7ED321',
      eyeType: 2,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 6,
      mouthCurve: 0.9,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'powering-down',
    name: 'Apagado',
    category: 'Ciclo de producto',
    description: 'Óvalo negro con ojos cerrándose lentamente',
    data: {
      silhouette: 'wide-oval',
      color: '#18181B',
      eyeType: 28,
      eyeOpen: 0.1,
      eyeScale: 0.8,
      mouthType: 3,
      mouthCurve: 0,
      hasBrows: false,
      transitionType: 'gentle',
    },
  },

  // --- MORFOS DE AGENTE (3) ---
  {
    id: 'orbit',
    name: 'Órbita',
    category: 'Morfos de agente',
    description: 'Óvalo azul girando en órbita constante',
    data: {
      silhouette: 'oval',
      color: '#4A90E2',
      eyeType: 31,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 0,
      mouthCurve: 0.2,
      spin: true,
      transitionType: 'smooth',
    },
  },
  {
    id: 'radar',
    name: 'Radar',
    category: 'Morfos de agente',
    description: 'Píldora menta con espiral de barrido de radar',
    data: {
      silhouette: 'pill-vertical',
      color: '#50E3C2',
      eyeType: 18,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 10,
      mouthCurve: 0,
      gazeX: 8,
      gazeY: -4,
      transitionType: 'snappy',
    },
  },
  {
    id: 'progress',
    name: 'Progreso',
    category: 'Morfos de agente',
    description: 'Óvalo dorado con destellos de avance continuo',
    data: {
      silhouette: 'elongated-oval',
      color: '#FFD600',
      eyeType: 24,
      eyeOpen: 1.0,
      eyeScale: 1.05,
      mouthType: 5,
      mouthCurve: 0.7,
      transitionType: 'smooth',
    },
  },

  // --- INTERACCIÓN (4) ---
  {
    id: 'idle',
    name: 'Reposo',
    category: 'Interacción',
    description: 'Círculo verde neutro y balanceado',
    data: {
      silhouette: 'circle',
      color: '#7ED321',
      eyeType: 0,
      eyeOpen: 1.0,
      eyeScale: 1.0,
      mouthType: 0,
      mouthCurve: 0.0,
      mouthOpen: 0.0,
      cheek: 0,
      hasBrows: false,
      transitionType: 'smooth',
    },
  },
  {
    id: 'near',
    name: 'Cercanía',
    category: 'Interacción',
    description: 'Mirada atenta cuando el cursor se aproxima',
    data: {
      silhouette: 'circle',
      color: '#7ED321',
      eyeType: 0,
      eyeOpen: 1.0,
      eyeScale: 1.05,
      mouthType: 0,
      mouthCurve: 0.3,
      cheek: 0.2,
      transitionType: 'smooth',
    },
  },
  {
    id: 'hover',
    name: 'Cursor Encima',
    category: 'Interacción',
    description: 'Sonrisa y sonrojo al pasar el ratón por encima',
    data: {
      silhouette: 'circle',
      color: '#7ED321',
      eyeType: 1,
      eyeOpen: 1.0,
      eyeScale: 1.1,
      mouthType: 0,
      mouthCurve: 0.6,
      cheek: 0.5,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
  {
    id: 'click',
    name: 'Clic / Toque',
    category: 'Interacción',
    description: 'Reacción alegre al hacer clic con rebote',
    data: {
      silhouette: 'circle',
      color: '#7ED321',
      eyeType: 2,
      eyeOpen: 1.0,
      eyeScale: 1.15,
      mouthType: 6,
      mouthCurve: 0.9,
      mouthOpen: 0.6,
      cheek: 0.8,
      bounce: true,
      transitionType: 'bouncy',
    },
  },
];
